version: "3"

services:
  frontend-challenge:
    container_name: frontend-challenge
    image: node:lts
    working_dir: "/app"
    volumes:
      - ./:/app
    ports:
      - 3005:3005
    command: bash -c "sh .docker/node/entrypoint.sh"